
spring:
  application:
    name: Enotes_API_Service

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: niladrikar97@gmail.com
    password: ghhz fmpk zjsm cjcz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc 
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans

file:
  upload:
    path: notes/
---
profiles:
  active: dev



